<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);BlazorApp1\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\partidos.json" />
    <None Remove="Data\goleadores2026.json" />
    <None Remove="Data\pronosticos.json" />
    <None Remove="Data\quinielas.json" />
    <None Remove="Data\resultados2026.json" />
    <None Remove="Data\selecciones.json" />
    <None Remove="Data\usuarios.json" />
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Images\Banderas\*.png" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\partidos.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\goleadores2026.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\pronosticos.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\quinielas.json" />
    <Content Include="Data\resultados2026.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\selecciones.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Data\usuarios.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Banderas\*.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Evidences\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.33.0.1635">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
